### ISSUE TITLE
how do I know if the training has started?

### ISSUE THREAD

**Issue by DoguCatto** [ashleykleynhans/kohya-docker#1]
I made all the folders and uploaded the data like I do on my local PC
but still get this error in th Jupyter- Image folder does not exist

**Comment by ashleykleynhans** [comment]
@DoguCatto Are you using this template on RunPod?

If so, the instructions for viewing the log are in the README for the template and also for your pod:

Open a terminal and run the following command:

```bash
tail -f /workspace/logs/kohya_ss.log
```
