### ISSUE TITLE
Kohya webUI is not loading

### ISSUE THREAD

**Issue by TimLinton** [ashleykleynhans/kohya-docker#10]
I installed the docker container like so:
sudo docker run -d  --name kohya  --gpus all   -v '/kohya/kohya-docker/workspace'  -p 3000:3001   -p 8000:8000   -p 8888:8888   -p 2999:2999   ashleykza/kohya:latest

also without the name:
sudo docker run -d  --name kohya  --gpus all   -v '/kohya/kohya-docker/workspace'  -p 3000:3001   -p 8000:8000   -p 8888:8888   -p 2999:2999   ashleykza/kohya:latest

I'm able to see Runpod, jupyterLab, and the runpod uploader, but the kohya_ss webui will not load. I am on localhost:3000. I tried looking on another device on my network and i am unable to access the page, logs  just say "container is READY". It was working yesterday. I have recreated the container a few times. 

`Starting Jupyter Lab...
Jupyter Lab started
Starting RunPod Uploader...
RunPod Uploader started
Running pre-start script...
Template version: 24.0.6
Syncing kohya_ss to workspace, please wait...
Syncing Application Manager to workspace, please wait...
Fixing venv...
Fixing venv. Old Path: /kohya_ss/venv  New Path: /workspace/kohya_ss/venv
Configuring accelerate...
Starting Kohya_ss Web UI
Kohya_ss started
Log file: /workspace/logs/kohya_ss.log
All services have been started
RUNPOD_PUBLIC_IP is not set. Skipping FileZilla configuration.
Updating rclone...
2024/04/27 22:49:13 NOTICE: rclone is up to date
Exporting environment variables...
Container is READY!
`

**Comment by ashleykleynhans** [comment]
Works fine for me, I don't provide support if you can't get it working, figure it out.
