### ISSUE TITLE
Add cron

### ISSUE THREAD

**Issue by rafstahelin** [ashleykleynhans/kohya-docker#11]
Would love Cron added in order to schedule regular rclone transfers during training. Checkpoint file size is huge. Helps to start transferring in parts regularly during training

**Comment by rafstahelin** [comment]
trying to install cron on jupyterlab, but seems i cant install without Systemd, but running cron service wont run without it. Not sure what to do to automate processes without cron, pity @ashleykleynhans

**Comment by ashleykleynhans** [comment]
Cron works perfectly fine, you must be starting it incorrectly.

```bash
apt update
apt install cron
service cron start
```

**Comment by ashleykleynhans** [comment]
Cron service has now been added to the image and it starts automatically when the container starts.

**Comment by rafstahelin** [comment]
You're a star Ashley!!
