### ISSUE TITLE
Is it normal that i cant see logs of the training ? 

### ISSUE THREAD

**Issue by Dervlex** [ashleykleynhans/kohya-docker#13]
As the title says.

I get it to work, that it train (It safes samples and safetensors of my lora) but i didnt get a log of what it does ^^

**Comment by ashleykleynhans** [comment]
Read the README.

**Comment by Dervlex** [comment]
I read it. 

Isnt really helping.

Thx for that awesome answer.

You mean the part of (You have to edit... ? ) 

I just want to know how i get a view on the console of kohya.

**Comment by ashleykleynhans** [comment]
READ THE README, YOU DID NOT READ IT!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
