### ISSUE TITLE
How to view tensorboard when training?

### ISSUE THREAD

**Issue by WetOnTheWater** [ashleykleynhans/kohya-docker#15]
When training lora's via kohya gui, there's an option to start tensorboard. Believe there needs to be a port to connect to view the tensorboard. 

Any guidance greatly appreciated!

**Comment by ashleykleynhans** [comment]
Set your W&B API key and use that instead, its much better than Tensorboard and you can compare experiments side by side, there is no reason to want to use Tensorboard.

**Comment by ashleykleynhans** [comment]
Tenssorboard has been added on port 6006.

**Comment by WetOnTheWater** [comment]
Thank you! Only realized there was a wandb option when you mentioned it, super useful.
