### ISSUE TITLE
Old school issue popping up

### ISSUE THREAD

**Issue by duskfallcrew** [ashleykleynhans/kohya-docker#2]
This i get when i'm trying to do the log thing

    return buttonbox(msg=msg,
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/easygui/boxes/button_box.py", line 95, in buttonbox
    bb = ButtonBox(
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/easygui/boxes/button_box.py", line 147, in __init__
    self.ui = GUItk(msg, title, choices, images, default_choice, cancel_choice, self.callback_ui)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/easygui/boxes/button_box.py", line 263, in __init__
    self.boxRoot = tk.Tk()
  File "/usr/lib/python3.10/tkinter/__init__.py", line 2299, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

I"m not joking you, this worked less than a month ago, i got an SDXL lora running for 0.9 less than three weeks ago

**Comment by ash-bluepollution95** [comment]
Weirder still, NOTHING works when i try and actually train anything - apart from loading the json file, and i'm not joking this template worked PERFECTLY -- on runpod especially last time ---

I'll give it a whirl on vast, and see if it does the same thing.
I'm not MAD at anyone.. 

i'm just -- sick of being stuck to using colab only. (as i can't train locally)

**Comment by ash-bluepollution95** [comment]
AH it may have been my machine i picked!
I'm on an RTX 3090 right now on cloud -- and the log command worked so maybe it's finickey depending on the machine! i'll report back if i have more issues.

Sorry for being so loud, i do understand y'all are SUPER busy o.o

**Comment by ashleykleynhans** [comment]
Please log an issue for this project:

https://github.com/bmaltais/kohya_ss
