### ISSUE TITLE
Building a new docker image

### ISSUE THREAD

**Issue by lchunleo** [ashleykleynhans/kohya-docker#5]
Hi 
 i used the built docker image ashleykza/kohya:latest to run and all is fine. However, when trying to train, i hit into issue as i believe there is some incompatibility of CUDA 11.8 with my machine. Am using CUDA 11.6 on my machine. Can i check is the Dockerfile in this repo the same one which is used to built the "ashleykza/kohya:latest" as i have issue with the #0 324.1 E: Couldn't find any package by glob 'python3.10-venv'" which python3.10-venv is one of the packages to installed. Thanks

**Comment by ashleykleynhans** [comment]
This works for me and any other version of CUDA besides 11.8 is not supported.
